#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyriadMobile.Lantern.Example.Resource", IsApplication=true)]

namespace MyriadMobile.Lantern.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int beacon_far = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int beacon_immediate = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int beacon_near = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int beacon_unkown = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int lnr_beacon_root = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int lv_beacons = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int swtScan = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int tv_beacon_distance = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int tv_beacon_expiration = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int tv_beacon_mac = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int tv_beacon_major = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int tv_beacon_minor = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int tv_beacon_rssi = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int tv_beacon_uuid = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int tv_status = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BeaconItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int expiration = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int fast_scanning = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int mac = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int major = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int minor = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int not_scanning = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int off = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int proximity = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int rssi = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int scan_toggle = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int scanning = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int uuid = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
